export const designConfig = {
  layout: {
    pageShell: "h-[calc(100vh-86px)] overflow-y-auto custom-scrollbar bg-[var(--vendor-page-bg)]",
    pageInner: "max-w-[1700px] mx-auto px-[var(--vendor-page-x)] py-[var(--vendor-page-y)]",
    pageInnerTight: "max-w-[1700px] mx-auto px-4 sm:px-6 lg:px-8 py-6",
    sectionGap: "space-y-6",
    gridGap: "gap-6",
    formGrid: "grid grid-cols-1 md:grid-cols-2 gap-6",
    twoColumnForm: "grid grid-cols-1 lg:grid-cols-12 gap-8 items-start",
    mainColumn: "lg:col-span-9 space-y-6",
    sideColumn: "lg:col-span-3 space-y-6 lg:sticky lg:top-8",
  },
  type: {
    pageTitle: "text-[var(--vendor-title-text)] font-bold text-[var(--vendor-text)] uppercase tracking-tight",
    pageSubtitle: "text-[var(--vendor-subtitle-text)] text-[var(--vendor-text-muted)] mt-1 font-medium",
    sectionTitle: "text-[var(--vendor-section-title-text)] font-bold text-[var(--vendor-text)] uppercase tracking-wide",
    sectionSubtitle: "text-[var(--vendor-caption-text)] text-[var(--vendor-text-muted)] font-semibold uppercase tracking-wide",
    cardTitle: "text-[var(--vendor-form-section-title-text)] font-semibold text-[var(--vendor-text)] uppercase tracking-wide",
    label: "text-[var(--vendor-form-label-text)] font-semibold text-[var(--vendor-text-muted)] uppercase tracking-wide",
    body: "text-[var(--vendor-form-input-text)] font-medium text-[var(--vendor-text)]",
    helper: "text-[var(--vendor-form-help-text)] font-medium text-[var(--vendor-text-muted)]",
    error: "text-[var(--vendor-form-help-text)] font-semibold text-rose-500 uppercase tracking-wide",
    tableText: "text-[var(--vendor-table-text)] font-medium text-[var(--vendor-text)] tracking-normal",
    tableStrong: "text-[var(--vendor-table-text)] font-semibold text-[var(--vendor-text)] tracking-normal",
    tableMuted: "text-[var(--vendor-table-text)] font-medium text-[var(--vendor-text-muted)] tracking-normal",
    caption: "text-[var(--vendor-caption-text)] font-medium text-[var(--vendor-text-muted)] tracking-normal",
  },
  surface: {
    page: "bg-[var(--vendor-page-bg)]",
    panel: "bg-[var(--vendor-panel-bg)] dark:bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)]",
    panelPadded: "p-[var(--vendor-panel-padding)]",
    panelHeader: "border-b border-[var(--vendor-border)] pb-4 mb-6",
    tablePanel: "bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)] overflow-hidden",
    toolbar: "bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)] p-3",
    subtle: "bg-[var(--vendor-table-row-alt)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)]",
  },
  control: {
    input: "rounded-[var(--vendor-radius-control)] text-[var(--vendor-control-text)] border-[var(--vendor-border)] bg-[var(--vendor-panel-bg)]/20 focus:border-[var(--vendor-primary-btn)]/20 focus:ring-4 focus:ring-[var(--vendor-primary-btn)]/10",
    search: "h-9 w-full pl-10 bg-[var(--vendor-page-bg)] transition-all text-[12px] font-medium rounded-[var(--vendor-radius-control)]",
    select: "rounded-[var(--vendor-radius-control)] text-[var(--vendor-control-text)] border-[var(--vendor-border)]",
    button: "rounded-[var(--vendor-radius-control)] text-[var(--vendor-control-text)] font-bold",
    actionButton: "h-10 gap-2 uppercase tracking-wide text-[var(--vendor-control-text)] font-semibold",
    iconButton: "rounded-[var(--vendor-radius-control)]",
    tabs: "rounded-[var(--vendor-radius-control)] text-[var(--vendor-control-text)] font-semibold",
    switchRow: "flex items-center justify-between p-4 rounded-[var(--vendor-radius-panel)] border border-[var(--vendor-border)] bg-[var(--vendor-table-row-alt)]",
  },
  data: {
    tableWrapper: "bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)] overflow-hidden",
    table: "w-full min-w-[1100px] border-separate border-spacing-0 text-left text-[var(--vendor-table-text)]",
    tableHead: "sticky top-0 z-20 bg-[var(--vendor-table-head-bg)] shadow-sm",
    tableHeadRow: "border-b border-[var(--vendor-border)]",
    tableHeadCell: "px-[var(--vendor-table-x)] py-[var(--vendor-table-head-y)] text-[var(--vendor-table-head-text)] font-semibold uppercase tracking-normal text-[var(--vendor-text-muted)] align-middle whitespace-nowrap",
    tableBody: "divide-y divide-[var(--vendor-border)]",
    tableRow: "h-[var(--vendor-table-row-height)] transition-colors duration-200 even:bg-[var(--vendor-table-row-alt)] odd:bg-[var(--vendor-panel-bg)] hover:bg-[var(--vendor-table-row-hover)]",
    tableRowSelected: "bg-primary/10 hover:bg-primary/10",
    tableCell: "px-[var(--vendor-table-x)] py-[var(--vendor-table-row-y)] text-[var(--vendor-text)] align-middle",
    pagination: "shrink-0 px-4 py-3 bg-[var(--vendor-panel-bg)] border-t border-[var(--vendor-border)] flex items-center justify-between",
    empty: "px-6 py-24 text-center bg-[var(--vendor-table-row-alt)] text-[var(--vendor-text-muted)]",
    loading: "p-20 text-center font-bold animate-pulse text-[var(--vendor-text-muted)] uppercase tracking-wide",
  },
  feedback: {
    success: "text-emerald-600 bg-emerald-50 border-emerald-200",
    warning: "text-amber-600 bg-amber-50 border-amber-200",
    danger: "text-rose-600 bg-rose-50 border-rose-200",
    info: "text-[var(--vendor-primary-btn)] bg-[var(--vendor-table-row-hover)] border-[var(--vendor-primary-btn)]/20",
    muted: "text-[var(--vendor-text-muted)] bg-[var(--vendor-table-row-alt)] border-[var(--vendor-border)]",
  },
  page: {
    shell: "h-[calc(100vh-86px)] overflow-y-auto custom-scrollbar bg-[var(--vendor-page-bg)]",
    inner: "max-w-[1700px] mx-auto px-[var(--vendor-page-x)] py-[var(--vendor-page-y)]",
  },
  panel: {
    base: "bg-[var(--vendor-panel-bg)] dark:bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)]",
    padded: "p-[var(--vendor-panel-padding)]",
    header: "border-b border-[var(--vendor-border)] pb-4 mb-6",
  },
  table: {
    wrapper: "bg-[var(--vendor-panel-bg)] border border-[var(--vendor-border)] rounded-[var(--vendor-radius-panel)] shadow-[var(--vendor-shadow-panel)] overflow-hidden",
    table: "w-full min-w-[1100px] border-separate border-spacing-0 text-left text-[var(--vendor-table-text)]",
    head: "sticky top-0 z-20 bg-[var(--vendor-table-head-bg)] shadow-sm",
    headRow: "border-b border-[var(--vendor-border)]",
    headCell: "px-[var(--vendor-table-x)] py-[var(--vendor-table-head-y)] text-[var(--vendor-table-head-text)] font-semibold uppercase tracking-normal text-[var(--vendor-text-muted)] align-middle whitespace-nowrap",
    body: "divide-y divide-[var(--vendor-border)]",
    row: "h-[var(--vendor-table-row-height)] transition-colors duration-200 even:bg-[var(--vendor-table-row-alt)] odd:bg-[var(--vendor-panel-bg)] hover:bg-[var(--vendor-table-row-hover)]",
    rowSelected: "bg-primary/10 hover:bg-primary/10",
    cell: "px-[var(--vendor-table-x)] py-[var(--vendor-table-row-y)] text-[var(--vendor-text)] align-middle",
    text: "text-[var(--vendor-table-text)] font-medium text-[var(--vendor-text)] tracking-normal",
    textStrong: "text-[var(--vendor-table-text)] font-semibold text-[var(--vendor-text)] tracking-normal",
    textMuted: "text-[var(--vendor-table-text)] font-medium text-[var(--vendor-text-muted)] tracking-normal",
    textTiny: "text-[var(--vendor-caption-text)] font-medium text-[var(--vendor-text-muted)] tracking-normal",
    codeBadge: "font-mono text-[var(--vendor-caption-text)] font-semibold border-[var(--vendor-border)]/60 dark:border-[var(--vendor-border)] text-[var(--vendor-text-muted)] bg-[var(--vendor-panel-bg)]/50 py-0.5",
  },
  form: {
    label: "text-[var(--vendor-form-label-text)] font-semibold text-[var(--vendor-text-muted)] uppercase tracking-wide",
    help: "text-[var(--vendor-form-help-text)] font-medium text-[var(--vendor-text-muted)]",
    input: "text-[var(--vendor-form-input-text)] font-medium",
    sectionTitle: "text-[var(--vendor-form-section-title-text)] font-semibold text-[var(--vendor-text)] uppercase tracking-wide",
    sectionSubtitle: "text-[var(--vendor-form-section-subtitle-text)] font-semibold text-[var(--vendor-text-muted)] uppercase tracking-wide",
  },
} as const;

export type DesignConfig = typeof designConfig;
